# This workflow publishes the extension to Chrome 
# To use this workflow, ensure you have the following secrets set in your repository:
# - EXTENSION_ID: The ID of your Chrome extension.
# - CLIENT_ID: The client ID for your Google API.
# - CLIENT_SECRET: The client secret for your Google API.
# - REFRESH_TOKEN: The refresh token for your Google API.

name: Publish to Chrome Web Stores

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Build Chrome extension
        run: npm run build:chrome

      - name: Create Chrome ZIP file
        run: zip -r chrome-extension.zip dist

      - name: Upload & release Chrome extension
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: chrome-extension.zip
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}

